secrets:
    data:
        SUPABASE_ANON_KEY: ENC[AES256_GCM,data:skc5BHQSrn/sUGs43qKGBC3Xt7q8SpF7okSjsp1LAWPs6KWX6FrFwc/4ZfHBnw==,iv:aNqfzE3OuBVWacm1GB4j7Ab/HIiLJcKIqKbFqKrwIk4=,tag:2IhTfxKNSYOi4XPxdpanGQ==,type:str]
        REDIS_PASSWORD: ENC[AES256_GCM,data:qXRrKGRLQy3B/j3iPjGTmqc9udK4xX4=,iv:SvLuSttu1mQ1CM8XCYffgE6pUkQBqM++dBy/ySuDzi0=,tag:t8o1HpiabzON+12Io/5Zvw==,type:str]
        UPLOAD_SECRET: ENC[AES256_GCM,data:s7OYa9BAkolbsHALh6kDrK+YQHKS/L2y4Uc1NhABP3VTdtXcFrxK/Y8vSQ==,iv:cJYFXMYh8DJHt3PtSfTcGwI+skhsDQIAHFjaNNkz6ho=,tag:BmJYZbJXFEi4fdGuL7T5PQ==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/varuna-400921/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-02-25T14:31:32Z"
          enc: CiQA/cVY+2v4/9iA/DzfRG//njSu64xt5KfZpXt5WexUxtIncL8SSQAXYxKUD6sidzqKOug/k8F20siI1ggi6132n52QW74hE+UqpajwFg3H18MLj6xKrZ0ffBwPqd1dnZs1P/gIL5BqFRD3Cha31Fc=
    lastmodified: "2026-02-25T14:31:33Z"
    mac: ENC[AES256_GCM,data:QGdFrbvZ0PxUIerAbo5RNslkfLzzEYEWKjQRQX+0+e3Cqq3ZufLIOo11Ewm20XNfwV+Px4U+Ei8bmi8+AnutdvVUYVOK2QBzGrs5UnQPsWIxn3Ku13TjxxCuT7PD1C8Zch8vE4w6JsL7q/gV46GYyl+IPqhXPMte7xzzYqGbJ1M=,iv:vqdbvO/t4juqdN2qox4M7mTajYOY5ox1rep88qlVPPc=,tag:JSe/gnEaXkuOIRBVKdMRXg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
