secrets:
    data:
        SUPABASE_ANON_KEY: ENC[AES256_GCM,data:G0133IELjhopUvR4RyNK++e1yZEI/+TcDAjxpxLDRT/7mdrDpmv/OhQA4OwupA==,iv:jwc+s1eewq7wMyeuaYN0EUUN5W3PnCmHL/dworfxNSY=,tag:PzN7wu6mv09Vg2amjKqmiw==,type:str]
        SUPABASE_URL: ENC[AES256_GCM,data:kbPtxuERBQnnkdA1jZttFZfP40W1GhPiOVTNyzWQF5+qFikwDvk37w==,iv:zsH4J58U8PPQai3gGvTLXO13C0a9uxbqqCW00pjlch0=,tag:p1q07k/cqDKYzzcQyEefPQ==,type:str]
        REDIS_SENTINEL_ENDPOINTS: ENC[AES256_GCM,data:TVzm6CBXI8BhCELne88ygHMaiQZcxeTwHUbw7qhZPNc41hg=,iv:QP2lrMEsMEZHqCqQNywGUxgbmb8HBycUGj3pP2b8vwg=,tag:sp8NKF2q8LOJJg/fGmhxbQ==,type:str]
        REDIS_SENTINEL_MASTER_NAME: ENC[AES256_GCM,data:ok5ySd/JcW4=,iv:vCIUZyvuGwlu5laCUHIBq3gt9XSiTXxqY/wo22G5OtE=,tag:WSQ0qfvDmck5nsD4UXEatQ==,type:str]
        REDIS_PASSWORD: ENC[AES256_GCM,data:Cgx61Unnp8BCiYRPhLhqjTv7gzp/72M=,iv:IUTcAexUCiB3iR38OtIceeKX+yo/MifBnBCCJz/AtDA=,tag:4OXaJjosbnbZlQL5WtewMg==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/varuna-400921/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-02-24T17:16:29Z"
          enc: CiQA/cVY+wxwbn3to4SujOzX8LvgAMs5XQ3uZ6fzfY4YaAu5bkISSQAXYxKUC27tVeFnPGIN5cht68JZq3LLkXFSHLg0TOge/iIswyoNgsBZKnA9mqXL28d02N4eR1E24UhlBzMPPcw3V1AY3cY+wY8=
    lastmodified: "2026-02-24T18:14:37Z"
    mac: ENC[AES256_GCM,data:BXAGjvRIPY+pZ9qU2tIr6lrcIW0sxnRmEGrEY6bT9g9RdxrmMl341U6Kx94v6bvc60J8wo2V9DN4uh6raQ4dDcPq5IPmcX3q+TAMuUkHXigFgxEdOcMC22fG/3KzloQOlvNJPtJ1RdZvFl35cIvmCRcmLwZGNKDUp4//Cfdr6Pg=,iv:VMEyxU8kqY0sSRVZO3IwhmN01Qa8ijpmyMhUSbGWf/g=,tag:cgfofdnDfFPXUlNuELLKmg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
