secrets:
    data:
        SUPABASE_ANON_KEY: ENC[AES256_GCM,data:O/gqSYAPhpJB4WMAr7D9HnkLT+NjSwN9jcMBW9/MXGpbRxFB72+hY/AIWHvh6A==,iv:fcR1gyF8YBRmYYI8z79r10NVL0KlQnvt6/DCV2x7uXI=,tag:RyWgufxfiFez/LPge96crQ==,type:str]
        SUPABASE_URL: ENC[AES256_GCM,data:xGylUJThxPDcaMnpdKfpN1X3tq+zp+eTLGEcXiGGKTIByjV0bZxuow==,iv:0BkTS59QCId/ZykaZKPy0hUK/UDTEIRlHV6cBerD/0A=,tag:7ZiBQMNmMCW5Kb7rH659yA==,type:str]
        REDIS_SENTINEL_ENDPOINTS: ENC[AES256_GCM,data:TVzm6CBXI8BhCELne88ygHMaiQZcxeTwHUbw7qhZPNc41hg=,iv:QP2lrMEsMEZHqCqQNywGUxgbmb8HBycUGj3pP2b8vwg=,tag:sp8NKF2q8LOJJg/fGmhxbQ==,type:str]
        REDIS_SENTINEL_MASTER_NAME: ENC[AES256_GCM,data:ok5ySd/JcW4=,iv:vCIUZyvuGwlu5laCUHIBq3gt9XSiTXxqY/wo22G5OtE=,tag:WSQ0qfvDmck5nsD4UXEatQ==,type:str]
        REDIS_PASSWORD: ENC[AES256_GCM,data:Cgx61Unnp8BCiYRPhLhqjTv7gzp/72M=,iv:IUTcAexUCiB3iR38OtIceeKX+yo/MifBnBCCJz/AtDA=,tag:4OXaJjosbnbZlQL5WtewMg==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/varuna-400921/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-02-24T17:16:29Z"
          enc: CiQA/cVY+wxwbn3to4SujOzX8LvgAMs5XQ3uZ6fzfY4YaAu5bkISSQAXYxKUC27tVeFnPGIN5cht68JZq3LLkXFSHLg0TOge/iIswyoNgsBZKnA9mqXL28d02N4eR1E24UhlBzMPPcw3V1AY3cY+wY8=
    lastmodified: "2026-02-24T18:34:51Z"
    mac: ENC[AES256_GCM,data:inP810beROY5DGGB8ob295p17WnLQdtt9zDHBIFQMOMo6L1ZxYWZMyRpUVhau/gaNe9BrpDw+GldloTKiHEUgcZW+DyJXrbawEJ4vF+TJZUy8MPlQYGPal3yxNJ4T10w5IJQiKUeKtpuW8BvHAqQWlWlpbcd+WjVcXYkIn1HcOA=,iv:yS49RNbfZz1tDIvcyxAIcbth0RiFR6feUzOWi7rD5Rg=,tag:l5e3Mfz+4552qcVmdnk+Hw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
