secrets:
    data:
        SUPABASE_ANON_KEY: ENC[AES256_GCM,data:TPBkC9RX/Tn6pei+Cbd7f+EfejFzp7dLXKkytRgAKxr7CNxQJqx9XO1Bi8TVSg==,iv:1Ie5fD3RFvaiq3KMs04UXZXG+oLju+m0p1sTEHYMms8=,tag:owzx4EVq3+1WL9flFPpLLQ==,type:str]
        REDIS_PASSWORD: ENC[AES256_GCM,data:GK64VKLfEhey1jjqlbEiXZwP6KF7fI4=,iv:ODGYQmgAiVbRPDbXQGYYSwo3dtIyrjbz681fma3yoeY=,tag:THQ7mS2FPuUhm2VtVmvB9w==,type:str]
        UPLOAD_SECRET: ENC[AES256_GCM,data:4M2OaXCgIJg0cSSFOvdttDVuctzk5aCyMu3Fs9XHRwMfCjeT+Q7XQ3PNtw==,iv:z+lrBssnJWRqGJlKHfgeewlWxog3t6OK6HlT/K0/xAk=,tag:tGpLwPPlSzG+c7AM5ljqsQ==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/varuna-400921/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-02-25T14:31:36Z"
          enc: CiQA/cVY+5/ZUE7wfKz//4CDl0hFXJjShzUEAK+hemrvyQsuDt0SSQAXYxKUO5enAx362VwnW50rYKtIhUsqG/CeuEk+nakFUZFi2Cd9nKk1Pi1HnmU57BATBQU9HxMxZpDGZRHm3bvJ4Z2Hgflk1TA=
    lastmodified: "2026-02-25T14:31:36Z"
    mac: ENC[AES256_GCM,data:f/p2PcyeIPImu1/e1AKv9cj6i49Oj0pyon1qZo5mljtV99QmQt5dojw/h4o5LBUzIc+Ql9XvPrn63pAUMZisqHDw8uaoh2FOipNMcJ2Mj3wWT5xK5+uOTuZIwR8h7rOmheT8ITOG1ABQjqHCKhW4sP5hp8OvXEkHBDTFZ0qyGNA=,iv:/t7auUGCC3kk0YH57EGerlqF5gIgBgnmesHyubqtTkU=,tag:RapvhmFrrSE97nzyP90oCA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
