secrets:
    data:
        SUPABASE_ANON_KEY: ENC[AES256_GCM,data:TPBkC9RX/Tn6pei+Cbd7f+EfejFzp7dLXKkytRgAKxr7CNxQJqx9XO1Bi8TVSg==,iv:1Ie5fD3RFvaiq3KMs04UXZXG+oLju+m0p1sTEHYMms8=,tag:owzx4EVq3+1WL9flFPpLLQ==,type:str]
        REDIS_PASSWORD: ENC[AES256_GCM,data:GK64VKLfEhey1jjqlbEiXZwP6KF7fI4=,iv:ODGYQmgAiVbRPDbXQGYYSwo3dtIyrjbz681fma3yoeY=,tag:THQ7mS2FPuUhm2VtVmvB9w==,type:str]
        UPLOAD_SECRET: ENC[AES256_GCM,data:4M2OaXCgIJg0cSSFOvdttDVuctzk5aCyMu3Fs9XHRwMfCjeT+Q7XQ3PNtw==,iv:z+lrBssnJWRqGJlKHfgeewlWxog3t6OK6HlT/K0/xAk=,tag:tGpLwPPlSzG+c7AM5ljqsQ==,type:str]
        SENTRY_DSN: ENC[AES256_GCM,data:5/4I79Kl0yn3XwVF23aXFCDKdEfCK3mnFm1A3FbbF0H4bYXVcR2TyUuh9sFjekjKWqTRJD3GU5y0jqvLOMEauwz6DyFDnlnMLHIcZilfojGzMG7+cZOQWH9XgdECaWE=,iv:N4tu3bqLkX19pJ4MQNc0UrEAHbTts3VAXI978Iab/aU=,tag:JxNc5SEMIOBJr97wKWGUjQ==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/varuna-400921/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-02-25T14:31:36Z"
          enc: CiQA/cVY+5/ZUE7wfKz//4CDl0hFXJjShzUEAK+hemrvyQsuDt0SSQAXYxKUO5enAx362VwnW50rYKtIhUsqG/CeuEk+nakFUZFi2Cd9nKk1Pi1HnmU57BATBQU9HxMxZpDGZRHm3bvJ4Z2Hgflk1TA=
    lastmodified: "2026-03-12T10:36:04Z"
    mac: ENC[AES256_GCM,data:itQ4RmHONYLwjMhTphvG5GUAzKCSZPWEVsJHbWlljZ3qV0lqviel5H2+3Z2MOZMCi+kYKdZSm1s9bLB0Nh9+ZXZs+620wdr3TBiaLMSh6F/xEO3aYpgs0MR8L2Xsp8BBSHtg4CHPw+KtDn7mbkSU5D8BuzYtA1H5XeqBVs+tdXg=,iv:/IsLNB/SWvllO9KFUrlwruiWtuiGlOCGHs9GF6ECF8U=,tag:KoCZv0y2V3pipk/ZbqVurw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
