secrets:
    data:
        SUPABASE_ANON_KEY: ENC[AES256_GCM,data:5eLxAebxZ1frMGCC6WovRgCupE7c36FIC9UuBQVzL39gJQQeSIyDHQnZ8NUS1g==,iv:NE+zXzsdnnFBcVvC3ooyJ81FSoFoKLRotVMPA6USlNI=,tag:hZj6uZ3hmfszwiW0poUqTA==,type:str]
        REDIS_PASSWORD: ENC[AES256_GCM,data:qXRrKGRLQy3B/j3iPjGTmqc9udK4xX4=,iv:SvLuSttu1mQ1CM8XCYffgE6pUkQBqM++dBy/ySuDzi0=,tag:t8o1HpiabzON+12Io/5Zvw==,type:str]
        UPLOAD_SECRET: ENC[AES256_GCM,data:s7OYa9BAkolbsHALh6kDrK+YQHKS/L2y4Uc1NhABP3VTdtXcFrxK/Y8vSQ==,iv:cJYFXMYh8DJHt3PtSfTcGwI+skhsDQIAHFjaNNkz6ho=,tag:BmJYZbJXFEi4fdGuL7T5PQ==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/varuna-400921/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-02-25T14:31:32Z"
          enc: CiQA/cVY+2v4/9iA/DzfRG//njSu64xt5KfZpXt5WexUxtIncL8SSQAXYxKUD6sidzqKOug/k8F20siI1ggi6132n52QW74hE+UqpajwFg3H18MLj6xKrZ0ffBwPqd1dnZs1P/gIL5BqFRD3Cha31Fc=
    lastmodified: "2026-05-15T15:14:05Z"
    mac: ENC[AES256_GCM,data:3IlHCLpae+A3vQQEPO+bNUJ2t+wbXR2J2QvC4drQPlGQFSZiMAH9W50O26QJvO9W3V+GVQvOL4BnmMaHBEEIMeUsElI/P5wO1NuI0wC+oPL24oQxGEIv4dRJFjGLQgH2iFFu7QmDS1oo8WGHTxcFuUiznpqeALPG5MAkfXnorok=,iv:IloC7x00Xb0rBjMSOjuRPmvTu8rHpnmwLyma9Nyakj4=,tag:BrJRmABf472yPArX5UtchQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
