secrets:
    data:
        SUPABASE_ANON_KEY: ENC[AES256_GCM,data:5eLxAebxZ1frMGCC6WovRgCupE7c36FIC9UuBQVzL39gJQQeSIyDHQnZ8NUS1g==,iv:NE+zXzsdnnFBcVvC3ooyJ81FSoFoKLRotVMPA6USlNI=,tag:hZj6uZ3hmfszwiW0poUqTA==,type:str]
        REDIS_PASSWORD: ENC[AES256_GCM,data:nElcygvL4NfCe/iuNuDe7ZXtYQ0=,iv:2/NcAwE2GWmNcU2MUE16S2ZVv3/Ve4XgkhqIxo5veV4=,tag:dhGZ4ptYFXWS+YH4Jg5L2A==,type:str]
        UPLOAD_SECRET: ENC[AES256_GCM,data:s7OYa9BAkolbsHALh6kDrK+YQHKS/L2y4Uc1NhABP3VTdtXcFrxK/Y8vSQ==,iv:cJYFXMYh8DJHt3PtSfTcGwI+skhsDQIAHFjaNNkz6ho=,tag:BmJYZbJXFEi4fdGuL7T5PQ==,type:str]
sops:
    gcp_kms:
        - resource_id: projects/varuna-400921/locations/global/keyRings/sops/cryptoKeys/sops-key
          created_at: "2026-02-25T14:31:32Z"
          enc: CiQA/cVY+2v4/9iA/DzfRG//njSu64xt5KfZpXt5WexUxtIncL8SSQAXYxKUD6sidzqKOug/k8F20siI1ggi6132n52QW74hE+UqpajwFg3H18MLj6xKrZ0ffBwPqd1dnZs1P/gIL5BqFRD3Cha31Fc=
    lastmodified: "2026-06-17T11:06:05Z"
    mac: ENC[AES256_GCM,data:6jKF1HzhwGNJ6rl6qNdEmICOMavWmUVE771LdVPa5wFJZhNfawoPWUt2rkIaPFFhMAzzXpc7GSpToBVEbB8ch/+RWY7jtm3WXuyF0Vfq8+VgCrqB82z0+DKZJSZqzipizSsC4REVoZgMWh0QpgLrmng9s9iqSpKaDMwDq8wSa9E=,iv:cGjCoG+Xi0FR/QKG007WGoQRch+r0lqYpBu042LUW4k=,tag:2w4H3X4RqfPpocwj0ynltA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
